export interface IVehicleOptions {
    vehicleTypes: Array<string>,
    vehicleCategories: Array<string>,
    colors: Array<string>,
    fuelTypes: Array<string>,
    transmissionTypes: Array<string>,
    sellerTypes: Array<string>,
    carConditions: Array<string>,
    optionalFeatures: Array<string>,
    interiorFeatures: Array<string>,
    exteriorFeatures: Array<string>,
    safetyFeatures: Array<string>,
    comfortFeatures: Array<string>,
    years: Array<string>,
}
